compile: src/main.c src/Arquivo/Arquivo.c src/CPU/CPU.c src/Processos/Processos.c
	gcc -o TPII_SO src/main.c src/Fila/Fila.c src/MemoriaPrincipal/MemoriaP.c src/Arquivo/Arquivo.c src/CPU/CPU.c src/Processos/Processos.c -Wall -lm

