compile: src/main.c src/Arquivo/Arquivo.c src/CPU/CPU.c src/Processos/Processos.c
	gcc -o TPII_SO src/main.c src/Fila/Fila.c src/Memoria/Memoria.c src/MemoriaVirtual/MemoriaV.c src/Arquivo/Arquivo.c src/CPU/CPU.c src/Processos/Processos.c -Wall -lm

